name: SymphonyERP
description: "Symphony ERP Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8

  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2

  # State Management
  provider: ^6.1.1

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Image and Media
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  file_picker: ^8.1.4
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  open_filex: ^4.5.0

  # UI Components
  pull_to_refresh: ^2.0.0
  # flutter_local_notifications: ^16.3.0  # Temporarily disabled due to build issues

  # Utilities
  intl: ^0.20.2

  # Charts for analytics
  fl_chart: ^0.66.0

  # Internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Internationalization
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo/app_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lufga
      fonts:
        - asset: fonts/lufga/LufgaLight.ttf
          weight: 300
        - asset: fonts/lufga/LufgaLightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/lufga/LufgaRegular.ttf
          weight: 400
        - asset: fonts/lufga/LufgaItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/lufga/LufgaBold.ttf
          weight: 700
        - asset: fonts/lufga/LufgaBoldItalic.ttf
          weight: 700
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
